---

 - hosts: all
   become: yes

   tasks:

    - name: Install script
      template:
        src: /etc/ansible/roles/redis/templates/testweb.sh
        dest: /home/ansible-admin/testweb.sh
        mode: 0777
